# Generated by Django 5.2.7 on 2025-11-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Ber', 'Berlina'), ('SUV', 'SUV'), ('Cou', 'Coupé')], max_length=3),
        ),
    ]
